name: Run MiniTest
on: [push, pull_request]

jobs:
  run-minitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
          ruby-version: "2.7"
          rubygems: "latest"
      - name: Run tests
        run: |
          rake test --trace
